services:
  laminas:
    build: .
    ports:
     - "80:80"
    depends_on:
      - pgsql 
    volumes:
     - .:/var/www

  pgsql:
    image: postgres:12
    container_name: pgsql
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"   
